packages:
  - name: default
    functions:
      - name: enqueue-transcode
        runtime: nodejs:18
        web: true
        main: main
        limits:
          timeout: 60000
        environment:
          CORS_ORIGIN: "${CORS_ORIGIN}"
          ENQUEUE_API_URL: "${ENQUEUE_API_URL}"
          ENQUEUE_TOKEN: "${ENQUEUE_TOKEN}"
