# (same YAML as above)
name: Deploy to DigitalOcean Functions
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DO_NAMESPACE: fn-d01fb0c7-7b0a-498f-9f8f-68d5f5dd0ab9
      REDIS_URL: ${{ secrets.REDIS_URL }}
      QUEUE_KEY: ${{ secrets.QUEUE_KEY }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci || npm i
      - name: Install & auth doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install serverless plugin
        run: doctl serverless install
      - name: Connect to Functions namespace
        run: doctl serverless connect "$DO_NAMESPACE"
      - name: Deploy
        run: doctl serverless deploy .
      - name: Show function URL
        run: doctl serverless functions get default/enqueue-transcode --url || true
